### ISSUE TITLE
data exploration

### ISSUE THREAD

**Issue by NikolaiKunewa** [Fosso/trackdecpred#3]
## Description
In: source/visualization

## Task list

* [x]  histogramical view of datasets

* [x]  mean, heat map etc.

* [x]  Find out how represent the data visually by research
